---
title: "Charlotte for Public Transit"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#0068b3"
      base_font:
        google: Roboto
      code_font:
        google: Source Code Pro
    orientation: columns
    vertical_layout: fill
#   runtime: shiny
---

```{css}
<style>
.navbar {
}
.navbar-brand {
  color:white;
}
</style>
```

```{r global, include=FALSE}
# load scripts
source("main.R")
source("accessibility.R")
```

Inputs {.sidebar}
-------------------------------------

* We demand that CATS:
  * **INCREASE** frequencies
  * **EXPAND** routes and schedules
  * **BUILD** shelters at all stops

```{r sidebar}
```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Service Schedule

```{r col1tab1}
ggplotly(date_servicepattern_plot)
```

### Headways

```{r col1tab2}
route_headways_plot
```

### Departures

```{r col1tab3}
stop_departures_plot
```

Column {data-width=350}
-----------------------------------------------------------------------

### Map

```{r col2tab1}

```

