---
title: "R Notebook"
output: html_notebook
---

TransitLand API Docs: https://www.transit.land/documentation/rest-api
CATS GTFS Feed: https://www.transit.land/feeds/f-dnq-charlotteareatransitsystem

Install packages
```{r}
install.packages("tidyverse")
install.packages("httr")
install.packages("jsonlite")
install.packages("httpcode")
```

Load libraries
```{r}
library(tidyverse)
library(httr)
library(jsonlite)
library(httpcode)
```

```{r}
apiKey <- 'UuYy96enokuUCSSBA6IC09nqGKKeVKfZ'
onestopID <- 'f-dnq-charlotteareatransitsystem'
getTransit.Land <- GET("https://transit.land//api/v2/rest/feeds/f-dnq-charlotteareatransitsystem/download_latest_feed_version?apikey=UuYy96enokuUCSSBA6IC09nqGKKeVKfZ")
print(getTransit.Land)
```

```{r}
content <- getTransit.Land[["content"]]

# Function to download and unzip data from an HTTP response
download_and_unzip <- function(response) {
  # Check for successful response
  if (content_status_code(response) == 200) {
    # Extract content as raw vector
    zipped_data <- content(response, as = "raw")
    
    # Create a temporary file path
    temp_file <- tempfile()
    
    # Write the raw data to the temporary file
    writeBin(zipped_data, temp_file)
    
    # Unzip the downloaded file
    tryCatch({
      unzip(zipfile = temp_file)
    }, error = function(e) {
      message("Error unzipping file:", e)
    })
    
    # Optional: Remove the temporary file (uncomment if needed)
    # unlink(temp_file)
  } else {
    message("Failed to download data:", content_status_code(response))
  }
}

# Example usage: Replace "GET(your_http_url)" with your actual HTTP request
download_and_unzip(getTransit.Land)
```